ph-ee-g2psandbox:
  ph-ee-engine:
    ingress:
      apiversion: "networking.k8s.io/v1"

    deployment:
      apiversion: "apps/v1"

    service:
      apiversion: "v1"

    secret:
      apiversion: "v1"

    configmap:
      apiversion: "v1"

    zeebe-cluster-helm:
      enabled: false
      global:
        elasticsearch:
          host: "ph-ee-elasticsearch"
      image:
        repository: camunda/zeebe
        tag: 1.1.0
      clusterSize: "1"
      partitionCount: "1"
      replicationFactor: "1"
      JavaOpts: "-Xms1g -Xmx8g -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:MaxRAMPercentage=25.0 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+PrintFlagsFinal"

      elasticsearch:
        enabled: false
      kibana:
        enabled: false

      extraInitContainers: |
        - name: init-ph-ee-kafka-exporter
          image: busybox:1.28
          command: ['/bin/sh', '-c']
          args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://paymenthub-ee-dev.s3.us-east-2.amazonaws.com/jars/exporter-1.0.0-SNAPSHOT.jar"; ls -al /exporters/']
          volumeMounts:
          - name: exporters
            mountPath: /exporters/

    zeebe-operate-helm:
      enabled: true
      image:
        repository: camunda/operate
        tag: 1.1.0
      global:
        elasticsearch:
          host: "ph-ee-elasticsearch"
          clusterName: "ph-ee-elasticsearch"
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
        path: /
        host: operate.sandbox.mifos.io
        tls:
          enabled: true

    camunda-platform:
      prometheusServiceMonitor:
        enabled: false

    redis:
      enabled: false

    elasticsearch:
      enabled: false
      #Single Node Solution
      clusterHealthCheckParams: "wait_for_status=yellow&timeout=100s"
      protocol: http
      master:
        readinessProbe:
          httpGet:
            allow-insecure: true
            username: elastic
            password: "{{ .Env.ELASTIC_PASSWORD }}"
            path: /_cluster/health?wait_for_status=yellow&timeout=5s
            port: 9200
          initialDelaySeconds: 30
      data:
        readinessProbe:
          httpGet:
            allow-insecure: true
            username: elastic
            password: "{{ .Env.ELASTIC_PASSWORD }}"
            path: /_cluster/health?wait_for_status=yellow&timeout=5s
            port: 9200
          initialDelaySeconds: 30
      # Shrink default JVM heap.
      esJavaOpts: "-Xmx512m -Xms512m"
      # Allocate smaller chunks of memory per pod.
      resources:
        requests:
          cpu: "100m"
          memory: "1024M"
        limits:
          cpu: "1000m"
          memory: "1024M"
      volumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 10Gi

    kibana:
      enabled: false
      readinessProbe:
        initialDelaySeconds: 45
        timeoutSeconds: 15
        successThreshold: 1
      protocol: http
      ingress:
        enabled: false
        className: "nginx"
        pathtype: "Prefix"
        annotations: { }
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        hosts:
          - host: analytics.sandbox.mifos.io
            paths:
              - path: /
        #tls: []
        #  - secretName: chart-example-tls
        #    hosts:
        #      - chart-example.local

    operations:
      enabled: true
      mysql:
        enabled: false

      auth:
        database: "tenants"
        username: "mifos"
        password: "password"
        rootPassword: "ethieTieCh8ahv"
      initdbScripts:
        setup.sql: |-
          CREATE DATABASE messagegateway;
          CREATE DATABASE `rhino`;
          CREATE DATABASE `gorilla`;
          GRANT ALL PRIVILEGES ON `rhino`.* TO 'mifos';
          GRANT ALL PRIVILEGES ON `gorilla`.* TO 'mifos';
          GRANT ALL ON *.* TO 'root'@'%';
          GRANT ALL PRIVILEGES ON messagegateway.* TO 'mifos';

    vouchers:
      enabled: true
      spring:
        datasource:
          url: "jdbc:mariadb://mysql.infra.svc.cluster.local:3306/voucher_management"
          username: "mifos"
          password: "password"

    ph_ee_connector_ams_mifos:
      enabled: true
      image: "docker.io/openmf/ph-ee-connector-ams-mifos:latest"
      imageTag: "latest"
      SPRING_PROFILES_ACTIVE: "fin12,bb"
      operations_app:
        datasource:
          host: "mysql.infra.svc.cluster.local"
      ams_local_enabled: true
      ams_local_interop_host: "https://fynams.sandbox.mifos.io/"
      ams_local_account_host: "https://fynams.sandbox.mifos.io/"
      ams_local_customer_host: "https://fynams.sandbox.mifos.io/"
      ams_local_auth_host: "https://fynams.sandbox.mifos.io/"
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: ams-mifos.sandbox.mifos.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: ph-ee-connector-ams-mifos
                    port:
                      number: 80
      deployment:
        annotations:
          deployTime: "{{ .Values.deployTime }}"

    ph_ee_connector_mojaloop:
      enabled: true
      image: "docker.io/openmf/ph-ee-connector-mojaloop:latest"
      imageTag: "latest"
      SPRING_PROFILES_ACTIVE: "bb"
      hostname: "mojaloop.sandbox.mifos.io"
      DFSPIDS: "gorilla,lion"
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: mojaloop.sandbox.mifos.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: ph-ee-connector-mojaloop-java
                    port:
                      number: 80
      deployment:
        annotations:
          deployTime: "{{ .Values.deployTime }}"

    mockpayment:
      enabled: true

    kafka:
      enabled: false
      image: "spotify/kafka"
      advertised:
        host: "kafka"
        port: "9092"
      deployment:
        annotations:
          deployTime: "{{ .Values.deployTime }}"

    channel:
      enabled: true
      image: "docker.io/openmf/ph-ee-connector-channel:latest"
      imageTag: "latest"
      hostname: "channel.sandbox.mifos.io"
      stub_hostname: "channel-gsma.sandbox.mifos.io"
      SPRING_PROFILES_ACTIVE: "bb,tenants"
      DFSPIDS: "rhino,gorilla"
      resources:
        requests:
          memory: "1M"
          cpu: "1m"
      redis:
        host: "redis-master.infra.svc.cluster.local"
        port: 6379
        password: ""
        idempotency:
          enabled: true
          keyFormat: "clientCorrelationId_tenant_api"
          apiList: "/channel/transfer,/channel/collection,/channel/gsma/transaction,/channel/transactionRequest"
      operations:
        url: "http://ops-bk.sandbox.mifos.io/api/v1"
        authEnabled: false
      tenantPrimary:
        clientId: "mifos"
        clientSecret: "password"
        tenant: "rhino"
      tenantSecondary:
        clientId: "mifos"
        clientSecret: "password"
        tenant: "gorilla"
      server:
        ssl:
          keyPassword: "password"
          keyStorePassword: "password"
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: channel.sandbox.mifos.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-channel"
                    port:
                      number: 8443
          - host: channel-gsma.sandbox.mifos.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-channel-gsma"
                    port:
                      number: 82
      deployment:
        annotations:
          deployTime: "{{ .Values.deployTime }}"


    operations_app:
      enabled: true
      image: "docker.io/openmf/ph-ee-operations-app:latest"
      imageTag: "latest"
      tenants: "rhino,gorilla"
      hostname: "ops-bk.sandbox.mifos.io"
      limits:
        cpu: "1000m"
        memory: "2G"
      secret:
        apiversion: "v1"
        datasource:
          username: "mifos"
          password: "password"
          host: "mysql.infra.svc.cluster.local"
          port: 3306
          schema: "tenants"
      datasource:
        username: "mifos"
        password: "password"
        host: "mysql.infra.svc.cluster.local"
        port: 3306
        schema: "tenants"
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: ops-bk.sandbox.mifos.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-operations-app"
                    port:
                      number: 80
      deployment:
        annotations:
          deployTime: "{{ .Values.deployTime }}"

    operations_web:
      enabled: true
      image: "docker.io/openmf/ph-ee-operations-web:latest"
      imageTag: "latest"
      hostname: "ops.sandbox.mifos.io"
      SPRING_PROFILES_ACTIVE: "bb"
      ingress:
        enabled: false
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: ops.sandbox.mifos.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-operations-web"
                    port:
                      number: 4200
    identity:
      hostname: "ops-bk.sandbox.mifos.io"

    ph_ee_connector_gsma:
      enabled: true
      image: "docker.io/openmf/ph-ee-connector-gsma:latest"
      imageTag: "latest"
      SPRING_PROFILES_ACTIVE: "bb"
      limits:
        cpu: "500m"
        memory: "512M"
      requests:
        cpu: "1m"
        memory: "1M"
      deployment:
        annotations:
          deployTime: "{{ .Values.deployTime }}"

    ph_ee_connector_slcb:
      enabled: false

    mpesa:
      enabled: false

    roster_connector:
      enabled: false

    paygops_connector:
      enabled: false

    notifications:
      enabled: true
      image: "docker.io/openmf/ph-ee-notifications:latest"
      imageTag: "latest"
      imagePullPolicy: "Always"
      SPRING_PROFILES_ACTIVE: "bb"
      LOGGING_LEVEL_ROOT: "INFO"
      MESSAGEGATEWAYCONFIG_HOST: "message-gateway"
      NOTIFICATION_LOCAL_HOST: "ph-ee-connector-notifications"
      limits:
        cpu: "1000m"
        memory: "2G"
      NOTIFICATION_SUCCESS_ENABLED: "false"
      NOTIFICATION_FAILURE_ENABLED: "true"
      hostname: "notifications.sandbox.mifos.io"
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: notifications.sandbox.mifos.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-notifications"
                    port:
                      number: 80
      deployment:
        annotations:
          deployTime: "{{ .Values.deployTime }}"

    connector_bulk:
      enabled: true
      image: "docker.io/openmf/ph-ee-bulk-processor:latest"
      imageTag: "latest"

      tenant: "rhino,gorilla"
      hostname: bulk-connector.sandbox.mifos.io
      aws:
        region: "ap-south-1"
        access_key: "<access_key>"
        secret_key: "<secret_key>"
      operations_app:
        contactpoint: "https://ops-bk.sandbox.mifos.io/"
        endpoints:
          batch_transaction: "/api/v1/batch/transactions"
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: bulk-connector.sandbox.mifos.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-bulk"
                    port:
                      number: 80
      deployment:
        annotations:
          deployTime: "{{ .Values.deployTime }}"

    zeebe_ops:
      enabled: true
      image: "docker.io/openmf/ph-ee-zeebe-ops:latest"
      imageTag: "latest"
      hostname: "zeebeops.sandbox.mifos.io"
      tenants: "rhino,gorilla"
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: zeebeops.sandbox.mifos.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-zeebe-ops"
                    port:
                      number: 80
      deployment:
        annotations:
          deployTime: "{{ .Values.deployTime }}"

    messagegateway:
      enabled: true
      DATASOURCE_URL: jdbc:mysql:thin://mysql.infra.svc.cluster.local:3306/messagegateway
      operations_app:
        datasource:
          host: "mysql.infra.svc.cluster.local"
      image: "docker.io/openmf/message-gateway:latest"
      imageTag: "latest"
      requests:
        cpu: "1m"
        memory: "1M"
      secret:
        value:
          api_key: "<api_key>"
          project_id: "<project_id>"
      hostname: "messagegateway.sandbox.mifos.io"
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: messagegateway.sandbox.mifos.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "message-gateway"
                    port:
                      number: 80
      deployment:
        annotations:
          deployTime: "{{ .Values.deployTime }}"

    importer_es:
      enabled: true
      image: "docker.io/openmf/ph-ee-importer-es:latest"
      imageTag: "33959ce8f4"
      elasticsearch_sslverification: false
      elasticsearch_security_enabled: false
      reporting:
        enabled: false

    importer_rdbms:
      enabled: true
      image: "docker.io/openmf/ph-ee-importer-rdbms:latest"
      imageTag: "latest"
      LOGGING_LEVEL_ROOT: "DEBUG"
      datasource:
        username: "mifos"
        password: "password"
        host: "mysql.infra.svc.cluster.local"
        port: 3306
        schema: "tenants"

    keycloak:
      enabled: true
      ingress:
        enabled: false
        ingressClassName: "kong"
        rules:
          - host: 'keycloak.sandbox.mifos.io'
            paths:
              - path: /
                pathType: Prefix
        tls: [ ]

    kong:
      enabled: true
      image:
        repository: revomatico/docker-kong-oidc
        tag: "latest"
      env:
        database: "postgres"
        pg_host: "moja-ph-postgresql"
        pg_user: "keycloak"
        pg_password: "keycloak"
        pg_database: "kong"
        plugins: "bundled,oidc"
      admin:
        enabled: true
        http:
          enabled: true
        tls:
          enabled: false
        ingress:
          enabled: false
          hostname: admin-kong.sandbox.mifos.io


  account_mapper:
    spring:
      datasource:
        url: jdbc:mysql:thin://mysql.infra.svc.cluster.local:3306/identity_account_mapper
        username: mifos
        password: password
    requests:
      cpu: "1m"
      memory: "1M"


